name: React App CI with Jenkins CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # ลดลงเป็นเวอร์ชันเดียวเพื่อให้สอดคล้องกับ Jenkins (node:16-buster-slim)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test -- --watchAll=false

    - name: Build
      run: npm run build

    # บันทึก artifacts จากการ build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/
    
    # เพิ่มขั้นตอนทริกเกอร์ Jenkins เมื่อ push ไปยัง master branch
    - name: Trigger Jenkins job
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      run: |
        curl -X POST \
             -H "Content-Type: application/json" \
             --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
             "${{ secrets.JENKINS_URL }}/job/simple-node-js-react-npm-app/build"
      continue-on-error: true

  # อีกชุดงานสำหรับ deployment (เปิดการใช้งานเมื่อต้องการ)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  #   
  #   steps:
  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: build-files
  #       path: build
  #  
  #   - name: Deploy to GitHub Pages
  #     uses: JamesIves/github-pages-deploy-action@v4
  #     with:
  #       folder: build
