name: React App CI with Jenkins CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test -- --watchAll=false

    - name: Build
      run: npm run build

    # บันทึก artifacts จากการ build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/
        
  # ทริกเกอร์ Jenkins สำหรับ CD เมื่อ push ไปยัง main หรือ master เท่านั้น
  trigger-jenkins:
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    
    steps:
    # ส่งไฟล์ build ไปยัง Jenkins
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: build
    
    # เก็บ build ไว้เป็น cache สำหรับใช้ใน Jenkins
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: build
        key: build-${{ github.sha }}
        restore-keys: |
          build-
    
    # ทริกเกอร์ Jenkins job
    - name: Trigger Jenkins
      run: |
        echo "CI workflow เสร็จสิ้นแล้ว - ทริกเกอร์ Jenkins"
        
        # โค้ดสำหรับการทริกเกอร์ Jenkins
        # หากคุณตั้งค่า Jenkins เรียบร้อยแล้ว ให้ถอดสัญลักษณ์ # ออกจากโค้ดด้านล่าง
        
        # แบบที่ 1: API trigger
        curl -X POST \
             -H "Content-Type: application/json" \
             --user "ytyt:ytyt1234" \
             "http://localhost:8080/job/simple-node-js-react-npm-app/build"
        
        # แบบที่ 2: webhook
        # curl -X POST "<JENKINS_WEBHOOK_URL>"
    
    # โนต: การทำงานร่วมกับ Jenkins
    - name: Jenkins integration note
      run: |
        echo "วิธีการตั้งค่าการทำงานร่วมกับ Jenkins:"
        echo "1. ตั้งค่า JENKINS_URL, JENKINS_USER, JENKINS_TOKEN ใน GitHub -> Settings -> Secrets -> Actions"
        echo "2. หรือตั้งค่า webhook ใน Jenkins และใช้ JENKINS_WEBHOOK_URL"
        echo "3. แก้ไขโค้ด GitHub Actions workflow ระบุคำสั่งทริกเกอร์ Jenkins ที่ถูกต้อง"
